# Generated by Django 4.2 on 2023-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
