# Generated by Django 4.2 on 2023-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
